# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dir_pb2 as dir__pb2


class DirectoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inserir = channel.unary_unary(
                '/dir.DirectoryService/Inserir',
                request_serializer=dir__pb2.InsertRequest.SerializeToString,
                response_deserializer=dir__pb2.InsertResponse.FromString,
                )
        self.Consulta = channel.unary_unary(
                '/dir.DirectoryService/Consulta',
                request_serializer=dir__pb2.QueryRequest.SerializeToString,
                response_deserializer=dir__pb2.QueryResponse.FromString,
                )
        self.Registro = channel.unary_unary(
                '/dir.DirectoryService/Registro',
                request_serializer=dir__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dir__pb2.RegisterResponse.FromString,
                )
        self.Termino = channel.unary_unary(
                '/dir.DirectoryService/Termino',
                request_serializer=dir__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dir__pb2.EndResponse.FromString,
                )


class DirectoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inserir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Termino(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inserir': grpc.unary_unary_rpc_method_handler(
                    servicer.Inserir,
                    request_deserializer=dir__pb2.InsertRequest.FromString,
                    response_serializer=dir__pb2.InsertResponse.SerializeToString,
            ),
            'Consulta': grpc.unary_unary_rpc_method_handler(
                    servicer.Consulta,
                    request_deserializer=dir__pb2.QueryRequest.FromString,
                    response_serializer=dir__pb2.QueryResponse.SerializeToString,
            ),
            'Registro': grpc.unary_unary_rpc_method_handler(
                    servicer.Registro,
                    request_deserializer=dir__pb2.RegisterRequest.FromString,
                    response_serializer=dir__pb2.RegisterResponse.SerializeToString,
            ),
            'Termino': grpc.unary_unary_rpc_method_handler(
                    servicer.Termino,
                    request_deserializer=dir__pb2.EmptyRequest.FromString,
                    response_serializer=dir__pb2.EndResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dir.DirectoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DirectoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inserir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dir.DirectoryService/Inserir',
            dir__pb2.InsertRequest.SerializeToString,
            dir__pb2.InsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Consulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dir.DirectoryService/Consulta',
            dir__pb2.QueryRequest.SerializeToString,
            dir__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Registro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dir.DirectoryService/Registro',
            dir__pb2.RegisterRequest.SerializeToString,
            dir__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Termino(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dir.DirectoryService/Termino',
            dir__pb2.EmptyRequest.SerializeToString,
            dir__pb2.EndResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
